import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const localeDirectory = resolve(root, 'sources/text/locales');
const generatedPath = resolve(root, 'sources/text/generated.ts');
const languageCodes = ['en', 'cn', 'de'];
const catalogs = Object.fromEntries(await Promise.all(languageCodes.map(async (code) => [
    code,
    JSON.parse(await readFile(resolve(localeDirectory, `${code}.json`), 'utf8')),
])));

function isSelect(value) {
    return Boolean(value && typeof value === 'object' && value.select);
}

function flatten(value, prefix = '', output = new Map()) {
    for (const [key, child] of Object.entries(value)) {
        const path = prefix ? `${prefix}.${key}` : key;
        if (typeof child === 'string' || isSelect(child)) {
            output.set(path, child);
        } else if (child && typeof child === 'object' && !Array.isArray(child)) {
            flatten(child, path, output);
        } else {
            throw new Error(`Invalid catalog value at ${path}`);
        }
    }
    return output;
}

function placeholders(message) {
    return [...message.matchAll(/(?<!\{)\{([A-Za-z][A-Za-z0-9_]*)\}(?!\})/g)]
        .map((match) => match[1])
        .sort();
}

function assertSameArray(actual, expected, context) {
    if (JSON.stringify(actual) !== JSON.stringify(expected)) {
        throw new Error(`${context}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
    }
}

const flattened = Object.fromEntries(languageCodes.map((code) => [code, flatten(catalogs[code])]));
const canonicalKeys = [...flattened.en.keys()].sort();

for (const code of languageCodes.slice(1)) {
    assertSameArray([...flattened[code].keys()].sort(), canonicalKeys, `${code} key schema drift`);
}

for (const key of canonicalKeys) {
    const canonical = flattened.en.get(key);
    for (const code of languageCodes.slice(1)) {
        const translated = flattened[code].get(key);
        if (isSelect(canonical) !== isSelect(translated)) {
            throw new Error(`${code}:${key} select shape differs from English`);
        }
        if (typeof canonical === 'string' && typeof translated === 'string') {
            assertSameArray(placeholders(translated), placeholders(canonical), `${code}:${key} placeholder drift`);
            continue;
        }
        if (isSelect(canonical) && isSelect(translated)) {
            if (canonical.select.param !== translated.select.param) {
                throw new Error(`${code}:${key} select parameter differs from English`);
            }
            const cases = Object.keys(canonical.select.cases).sort();
            assertSameArray(Object.keys(translated.select.cases).sort(), cases, `${code}:${key} select case drift`);
            for (const caseName of cases) {
                assertSameArray(
                    placeholders(translated.select.cases[caseName]),
                    placeholders(canonical.select.cases[caseName]),
                    `${code}:${key}.${caseName} placeholder drift`,
                );
            }
        }
    }
}

function paramsFor(value) {
    const names = new Set();
    if (typeof value === 'string') {
        placeholders(value).forEach((name) => names.add(name));
    } else {
        names.add(value.select.param);
        Object.values(value.select.cases).forEach((message) => {
            placeholders(message).forEach((name) => names.add(name));
        });
    }
    return [...names].sort();
}

const numericParameters = new Set([
    'count', 'hours', 'index', 'limit', 'max', 'maxMb', 'min', 'percent',
    'seconds', 'staged', 'unstaged',
]);
const booleanParameters = new Set(['enabled']);
const dynamicEntries = canonicalKeys
    .map((key) => [key, paramsFor(flattened.en.get(key))])
    .filter(([, params]) => params.length > 0);

function parameterType(name) {
    if (numericParameters.has(name)) return 'number';
    if (booleanParameters.has(name)) return 'boolean';
    if (name === 'code' || name === 'version' || name === 'total' || name === 'used') return 'string | number';
    return 'string';
}

const generated = `// Generated by scripts/validate-i18n.mjs. Do not edit by hand.\n\n`
    + `export type TranslationKey =\n${canonicalKeys.map((key) => `    | ${JSON.stringify(key)}`).join('\n')};\n\n`
    + `export interface TranslationParamsByKey {\n${dynamicEntries.map(([key, params]) => (
        `    ${JSON.stringify(key)}: { ${params.map((name) => `${name}: ${parameterType(name)}`).join('; ')} };`
    )).join('\n')}\n}\n\n`
    + `export type TranslationKeyWithParams = keyof TranslationParamsByKey;\n`
    + `export type TranslationParams<K extends TranslationKey> = K extends TranslationKeyWithParams\n`
    + `    ? TranslationParamsByKey[K]\n`
    + `    : never;\n`;

if (process.argv.includes('--write')) {
    await writeFile(generatedPath, generated);
} else {
    const existing = await readFile(generatedPath, 'utf8').catch(() => '');
    if (existing !== generated) {
        throw new Error('Generated i18n types are stale. Run: pnpm i18n:generate');
    }
}

console.log(`[i18n] ${canonicalKeys.length} keys validated for ${languageCodes.join(', ')}`);
