packages:
  - "packages/happyherd-app"
  - "packages/happyherd-control-agent"
  - "packages/happyherd-cli"
  - "packages/happyherd-server"
  - "packages/happyherd-server-self-host"
  - "packages/happyherd-wire"
  - "packages/happyherd-app-logs"
  - "packages/happyherd-agent"
  - "packages/codium"
  - "packages/expo-tailcat"

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build
