// Synthetic state/service adapters only. No product panel or visual component is replaced.
export const virtualModules = {
 'expo-router': `import React from 'react';const router={push(){},back(){},replace(){},navigate(){},setParams(){},canGoBack:()=>true};export const useRouter=()=>router;export {router};export const useLocalSearchParams=()=>new URLSearchParams(location.search).get('scene')==='terminal-invalid'?{}:new URLSearchParams(location.search).get('scene')==='terminal-confirm'?{'synthetic-public-key':''}:{id:'fixture-id',textId:'fixture-text'};export const useGlobalSearchParams=useLocalSearchParams;export const usePathname=()=>'/settings';export const useNavigation=()=>({setOptions(){},addListener:()=>()=>{},dispatch(){},getState:()=>({routes:[]})});export const useFocusEffect=callback=>React.useEffect(callback,[callback]);export const Stack=Object.assign(({children})=>children,{Screen:()=>null});export const Link=({children})=>children;`,
 '@react-navigation/native': `import React from 'react';export const useFocusEffect=callback=>React.useEffect(callback,[callback]);export const useNavigation=()=>({setOptions(){},addListener:()=>()=>{},dispatch(){},getState:()=>({routes:[]})});export const CommonActions={reset:x=>x};export const StackActions={popToTop:()=>({})};export const useIsFocused=()=>true;`,
 'react-native-safe-area-context': `export const useSafeAreaInsets=()=>({top:0,right:0,bottom:0,left:0});export const SafeAreaProvider=({children})=>children;export const SafeAreaView=({children})=>children;`,
 'react-native-reanimated': `import React from 'react';import {View,Text,ScrollView,Image} from 'react-native';const A={View,Text,ScrollView,Image,createAnimatedComponent:x=>x};export default A;export const useSharedValue=v=>React.useRef({value:v}).current;export const useAnimatedStyle=f=>f();export const useDerivedValue=f=>({value:f()});export const useAnimatedProps=f=>f();export const withTiming=v=>v;export const withSpring=v=>v;export const withDelay=(_,v)=>v;export const withRepeat=v=>v;export const withSequence=(...v)=>v.at(-1);export const cancelAnimation=()=>{};export const runOnJS=f=>f;export const interpolate=(x,a,b)=>b[0];export const interpolateColor=(x,a,b)=>b[0];export const Extrapolation={CLAMP:'clamp'};export const Easing={linear:x=>x,quad:x=>x,cubic:x=>x,bezier:()=>x=>x,out:x=>x,inOut:x=>x};export const FadeIn={duration:()=>({})};export const FadeOut=FadeIn;`,
 'react-native-worklets': `export const runOnJS=f=>f;`,
 'react-native-keyboard-controller': `import {KeyboardAvoidingView,ScrollView} from 'react-native';export {KeyboardAvoidingView};export const KeyboardAwareScrollView=ScrollView;export const useKeyboardHandler=()=>{};`,
 'expo-constants': `export default {statusBarHeight:0,expoConfig:{version:'0.1.0',extra:{}},appOwnership:'standalone'};`,
 'expo-clipboard': `export const setStringAsync=async()=>{};export const getStringAsync=async()=>'';`,
 'expo-crypto': `export const randomUUID=()=>crypto.randomUUID();export const getRandomBytes=n=>crypto.getRandomValues(new Uint8Array(n));export const digestStringAsync=async()=>'';export const CryptoDigestAlgorithm={SHA256:'SHA256'};export const CryptoEncoding={BASE64:'base64'};`,
 'expo-localization': `export const getLocales=()=>[{languageCode:'en',languageTag:'en-US'}];`,
 'expo-system-ui': `export const setBackgroundColorAsync=async()=>{};`,
 'expo-haptics': `export const impactAsync=async()=>{};export const selectionAsync=async()=>{};export const notificationAsync=async()=>{};export const ImpactFeedbackStyle={Light:'light',Medium:'medium'};export const NotificationFeedbackType={Success:'success'};`,
 'expo-document-picker': `export const getDocumentAsync=async()=>({canceled:true});`,
 'expo-status-bar': `export const StatusBar=()=>null;`,
 'react-native-webview': `export default ()=>null;`,
 '@/auth/AuthContext': `const credentials={token:'screenshot-fixture-token',secret:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='};export const useAuth=()=>({credentials,isAuthenticated:true,logout:async()=>{}});`,
 '@/sync/storage': `
 import React from 'react';import {settingsDefaults} from '@/sync/settings';
 const now=Date.now();
 export const machine={id:'fixture-id',active:true,activeAt:now,createdAt:now-86400000,updatedAt:now,metadata:{host:'review-workstation',displayName:'Review workstation',platform:'darwin',arch:'arm64',homeDir:'/Users/reviewer',happyCliVersion:'0.30.0',capabilitiesVersion:2,credentialManagementProtocolVersion:1,tools:{claude:{available:true},codex:{available:true}}},daemonState:{status:'running',pid:1234},metadataVersion:1,daemonStateVersion:1};
 export const session={id:'fixture-id',seq:1,active:true,activeAt:now,createdAt:now-3600000,updatedAt:now,metadata:{name:'KILV interface review',summary:{text:'Review warm light and dark surfaces',updatedAt:now},path:'/Users/reviewer/Projects/demo',host:'review-workstation',machineId:'fixture-id',flavor:'claude',harness:'claude',version:'0.30.0',os:'darwin',homeDir:'/Users/reviewer'},agentState:{controlledByUser:false,requests:{}},thinking:false,thinkingAt:0,presence:'online',draft:'',permissionMode:'default',modelMode:'default'};
 const machines=[machine],sessions=[session],projects=[];
 export const profile={id:'review-user',firstName:'Avery',lastName:'River',username:'avery-review',avatar:null,bio:'Synthetic profile for visual review',connectedServices:[],github:null};
 const friend={id:'friend-review',firstName:'Robin',lastName:'Chen',username:'robin-review',avatar:null,bio:'Building thoughtful interfaces',status:'friend',relationship:'friend'};
 const request={...friend,id:'friend-request',firstName:'Sam',lastName:'Lane',username:'sam-review',status:'pending',relationship:'pending'};
 const friends=[friend],requests=[request];
 export const artifact={id:'fixture-id',title:'Interface review notes',body:'# KILV interface review\\n\\nWarm materials and clear hierarchy.\\n\\n- Review typography and contrast\\n- Check desktop and mobile layouts\\n\\n## Sample command\\n\\n~~~sh\\npnpm --filter happy-app test\\n~~~\\n',isDecrypted:true,headerVersion:1,bodyVersion:1,seq:1,createdAt:now-86400000,updatedAt:now};
 const artifacts=[artifact,{...artifact,id:'second-artifact',title:'Release checklist',body:'Review notes'}];
 const settings={...settingsDefaults,experiments:true,avatarStyle:'brutalist',commanderProfilePictures:true,preferredLanguage:'en',voiceAssistantLanguage:'en'};
 const local={themePreference:new URLSearchParams(location.search).get('theme')||'light',devModeEnabled:false};
 const empty=[];const state={sessions:{'fixture-id':session},machines:{'fixture-id':machine},projects,settings,profile,artifacts:{'fixture-id':artifact},applyFriends(){},removeArtifact(){},applySettings(){},setSessionDraft(){},updateSessionPermissionMode(){},updateSessionModelMode(){}};
 export const storage=Object.assign(selector=>selector?selector(state):state,{getState:()=>state,setState(){},subscribe:()=>()=>{}});
 export const useSetting=k=>settings[k];export const useSettings=()=>settings;export const useSettingMutable=k=>React.useState(settings[k]);export const useLocalSetting=k=>local[k];export const useLocalSettingMutable=k=>React.useState(local[k]);
 export const useAllMachines=()=>machines;export const useMachine=()=>machine;export const useSessions=()=>sessions;export const useAllSessions=()=>sessions;export const useSession=()=>session;export const useProjects=()=>projects;export const useProject=()=>null;
 export const useProfile=()=>profile;export const useArtifacts=()=>artifacts;export const useArtifact=()=>artifact;export const useAcceptedFriends=()=>friends;export const useFriendRequests=()=>requests;export const useRequestedFriends=()=>empty;export const useFeedItems=()=>empty;export const useFeedLoaded=()=>true;export const useFriendsLoaded=()=>true;export const useRealtimeStatus=()=> 'disconnected';export const useEntitlement=()=>false;export const useIsDataReady=()=>true;export const useSocketStatus=()=> 'connected';export const useSessionMessages=()=>empty;export const useSessionUsage=()=>null;export const useMachineArtifacts=()=>empty;
 `,
 '@/sync/sync': `export const sync={refreshProfile:async()=>{},refreshMachines:async()=>{},refreshSessions:async()=>{},refreshArtifacts:async()=>{},fetchArtifact:async()=>{},loadArtifact:async()=>{},updateArtifact:async()=>{},createArtifact:async()=>({id:'fixture'}),getCredentials:()=>({token:'fixture'}),getSync:()=>({invalidate(){}}),getPurchases:()=>({}),applySettings(){}};`,
 '@/modal': `export const Modal={alert(){},confirm:async()=>false,prompt:async()=>null,show(){},hide(){}};`,
 '@/track': `export const trackFriendsConnect=()=>{};export const trackFriendsSearch=()=>{};export const trackFriendsProfileView=()=>{};export const trackPaywallButtonClicked=()=>{};export const trackWhatsNewClicked=()=>{};export const track=()=>{};`,
 '@/sync/apiFriends': `const user={id:'fixture-id',firstName:'Robin',lastName:'Chen',username:'robin-review',avatar:null,bio:'Building thoughtful interfaces',status:'friend',relationship:'friend',github:{login:'robin-review'}};export const searchUsersByUsername=async()=>[user,{...user,id:'new-friend',firstName:'Morgan',lastName:'Lee',username:'morgan-review',status:'none',relationship:'none'}];export const getUserProfile=async()=>user;export const sendFriendRequest=async()=>user;export const removeFriend=async()=>{};`,
 '@/sync/apiArtifacts': `export const deleteArtifact=async()=>{};`,
 '@/sync/apiGithub': `export const disconnectGitHub=async()=>{};export const getGitHubOAuthParams=async()=>({url:'https://example.invalid/oauth'});`,
 '@/sync/apiServices': `export const disconnectService=async()=>{};export const connectService=async()=>{};`,
 '@/sync/apiPush': `export const fetchPushTokens=async()=>[];`,
 '@/sync/apiVoice': `export const fetchVoiceUsage=async()=>({usedSeconds:245,limitSeconds:3600,conversationCount:4,conversationLimit:30});export const fetchVoiceTranscriptionKeyStatus=async()=>({configured:true,source:'user'});export const configureVoiceTranscriptionKey=async()=>({configured:true,source:'user'});export const removeVoiceTranscriptionKey=async()=>({configured:false,source:null});export const testVoiceTranscriptionKey=async()=>{};`,
 '@/sync/persistence': `export const retrieveTempText=()=> 'KILV interface review\\n\\nSelect and copy this sample text.\\n\\npnpm --filter happy-app test\\n\\nTypography stays readable on desktop and mobile.';export const getVoiceLocalCounters=()=>({dictationCount:12,dictationSeconds:245,voiceAssistantCount:4,voiceAssistantSeconds:245});export const resetVoiceLocalCounters=()=>{};export const loadSettings=()=>({settings:{preferredLanguage:'en'}});`,
 '@/hooks/useConnectAccount': `export const useConnectAccount=()=>({connectAccount:async()=>{},isConnecting:false});`,
 '@/hooks/useConnectTerminal': `export const useConnectTerminal=()=>({connectTerminal:async()=>{},isConnecting:false});`,
 '@/hooks/useNavigateToSession': `export const useNavigateToSession=()=>()=>{};`,
 '@/hooks/useWorktreeCleanup': `export const maybeCleanupWorktree=async()=>{};`,
 '@/hooks/useSessionQuickActions': `export const useSessionQuickActions=()=>({onArchive:async()=>{},onResume:async()=>{},onDuplicate:async()=>{},isArchiving:false,isResuming:false,isDuplicating:false});`,
 '@/utils/copySessionMetadataToClipboard': `export const copySessionMetadataToClipboard=async()=>{};export const copySessionMetadataAndLogsToClipboard=async()=>{};`,
 '@/sync/serverConfig': `export const getServerUrl=()=>location.origin;export const isUsingCustomServer=()=>false;`,
 '@/sync/apiSocket': `export const getHappyClientId=()=> 'fixture';export const apiSocket={on(){},off(){},emit(){},connected:true,machineRPC:async()=>({}),sessionRPC:async()=>({})};`,
 '@/utils/commanderAvatarUpload': `export class CommanderAvatarUploadError extends Error{};export const uploadCommanderAvatar=async()=>({});`,
 '@/utils/readFileBytes': `export const readFileBytes=async()=>new Uint8Array();`,
 '@/hooks/useCommanderAvatar': `export const useCommanderAvatar=()=>null;`,
 '@/sync/apiCredentials': `export class CredentialApiError extends Error{};export const listSavedCredentials=async()=>[{id:'credential-review',name:'Documentation token',type:'token',service:'docs.example.invalid',username:'reviewer',usage:['skills','mcp'],version:1,createdAt:Date.now(),updatedAt:Date.now()}];export const deleteSavedCredential=async()=>{};export const revealSavedCredential=async()=>({secret:'synthetic'});export const saveCredential=async()=>({});`,
 '@/sync/credentialOps': `export const listManagedCredentialAccounts=async()=>[{id:'account-review',provider:'claude',name:'Review account',email:'review@example.invalid',status:'ready',current:true,credentialVersion:1,active:true,createdAt:Date.now(),updatedAt:Date.now()}];export const cancelManagedCredentialLogin=async()=>{};export const getManagedCredentialLogin=async()=>({});export const removeManagedCredentialAccount=async()=>{};export const renameManagedCredentialAccount=async()=>{};export const startManagedCredentialLogin=async()=>({});export const submitManagedCredentialLoginCode=async()=>({});export const useManagedCredentialAccount=async()=>{};`,
 '@/utils/oauth': `export const generatePKCE=async()=>({codeVerifier:'fixture-verifier',codeChallenge:'fixture-challenge'});export const generateState=()=> 'fixture-state';export const parseCallbackUrl=()=>null;export const buildAuthorizationUrl=()=> 'https://example.invalid/oauth';export const exchangeCodeForTokens=async()=>({});`,
};
